FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build -- --configuration production

FROM nginx:alpine

COPY --from=build /app/dist/quiz-platform-ui/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/templates/default.conf.template

ENV MAIN_SERVICE_URL=http://main-service:5000

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
